### PR TITLE
Add analysis utility and histogram action to create van Hove plots

### PR DESCRIPTION
**Pull request by s6pepaul**
Tested on a few channels. It should work as intended. Maybe someone can double-check the uniqueness tracking.

### CODE REVIEW

**Comment by aaust** [comment]
I tested it with a simple call:

> dAnalysisActions.push_back(new DHistogramAction_vanHove(dComboWrapper, false, Proton, PiPlus, PiMinus, ""));

but the histograms have a peak in X at 0:

vanhove
vanhove_projection

In addition, the number of entries is not the same as a simple invariant mass histogram for all three particles

**Comment by aaust** [comment]
You can elegantly avoid all if-statements in the calculation of omega by using atan2:

`double omega = TMath::ATan2(-1.*sqrt(3.)*q1, 2.*q2+q1)`

**Comment by s6pepaul** [comment]
I checked the histogram action with the same reaction but used the kinfitted values. It looks fine to me. I think one should only use the vectors coming out of the kinematic fit to calculate the vH angle since the calculation of the coordinates implicitly requires that all particles are perfectly back-to-back. Nevertheless I don't quite understand at the moment why so many seem to be 0. I will look into this.

Regarding the number of entries: I use the photon and target to calculate the CM frame for the reaction and therefore also add it in the uniqueness tracking. If you only plot the inv mass histogram I would expect a different number since there the photon is not included. Am I wrong? Is it better to calculate the CM system from the three final state particles?

**Comment by gvasil** [comment]
Although I am not confident that I am "uniqueness tracking"  all of my histograms as I should, whenever I plot invariant mass histograms I also include the beam photon in the uniqueness tracking routine. This is because I apply accidental subtraction to these histograms and, therefore, I am using information that is related to the beam photon, despite the fact that it's not included in the histogram. 

Having said that, the histograms that are returned from the predefined HistogramActions are not accidental subtracted, so I wouldn't include the beam photon either in that case.

**Comment by s6pepaul** [comment]
You are right, George, the HistogramActions don't include the photon in the uniqueness tracking but maybe they should. As you pointed out, you need to include it if you want to do an accidental subtraction. At the moment the histograms from the actions are not useful for that. Also whenever one plots variables from the kin fitter one uses the photon information. So not including the photon in the tracking would mean to bias yourself towards out-of-time photons. I guess this isn't a discussion for this thread but something more general. In my opinion the beam photon always belongs in the uniqueness tracking but if people want me to take it out I am willing to do so when I update the pull request.

**Comment by aaust** [comment]
I can confirm that I do no longer see the artefact. However, Y changed its sign:

vanhove_corrected

**Comment by aaust** [comment]
To solve the issue with accidental subtraction, you could fill one in-time and one out-of time histogram. This can be implemented for all HistogramActions.

**Pull request merged**
