### PR TITLE
Added member variable dIsMC to default tree and modified call for acc…

### PR DESCRIPTION
**Pull request by aaust**
…idental scaling factor. It returns 1.0 for MC trees. The variable might be useful in other places, e.g. truth matching.

### CODE REVIEW

**Comment by sdobbs** [comment]
The isMC check is fine, but did we decide to handle the accidental scaling for MC like this, or rely on the CCDB?

**Comment by aaust** [comment]
Do we imagine values other than 1.0 for MC? I can also use the switch to query the MC variation from CCDB.

**Comment by sdobbs** [comment]
I don't know - how sure are we that it is exactly 1 in MC again?  Choosing the MC variation could also work.

I just made a PR for some code I was working on to allow setting the CCDB variation and timestamp, which I started after some conversation with Justin.  I could add some functions to set these values as well.  But I don't have a huge preference for how this could be done.

**Comment by aaust** [comment]
The latest commit permits to obtain a different accidental scaling factor for MC from the mc variation of CCDB, if that is ever needed. The default is backwards compatible and returns the default variation.

**Pull request merged**
