### PR TITLE
Make dE/dx and PID cut functions public

### PR DESCRIPTION
**Pull request by mikestaib**
Also make PID timing cuts function based (and public) to allow general shapes. Somehow my commit name is nsjarvis. Of well.

### CODE REVIEW

**Comment by pmattjlab** [comment]
This won't work.  In the Initialize() function you have to tell it to skip initializing the functions if they aren't nullptr, or else it'll rewrite them.

**Comment by mikestaib** [comment]
Sure it does. I have been using it. Call initialize first. Delete the function you don't want, then replace it with your own.

**Comment by pmattjlab** [comment]
If you add the action to the analysis action vector, then the DSelector library calls Initialize() automatically, wiping out what you set it to.  Plus, most people won't call Initialize() themselves.

**Comment by mikestaib** [comment]
Why'd you have to go and make it all fancy? I don't use the analysis action vector, so it works for me. I'll think about how to do it within that framework. In the meantime this shouldn't break existing user code.

**Pull request merged**
